org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Kotlin IC fails on Windows when the app is on D: and pub-cache plugins are on C:
kotlin.incremental=false
kotlin.incremental.java=false
kotlin.compiler.execution.strategy=in-process
